name: applanguefront

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^3.0.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  firebase_messaging: ^14.6.6
  firebase_storage: ^11.7.2
  firebase_core_platform_interface: ^5.0.0
  flutter_local_notifications: ^9.3.0 # Adjust version as needed
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.5.0
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  http: ^1.2.1
  convert: ^3.1.1
  get_storage: ^2.1.1
  geolocator: ^10.0.0
  permission_handler: ^10.4.3
  url_launcher: ^6.2.1
  wakelock_plus: ^1.1.3
  shared_preferences: ^2.2.0
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  image_picker: ^1.0.2
  flutter_typeahead:
  carbon_icons:
  logger:
  dartz:
  dio:
  flutter_svg:
  dotted_border:
  persistent_bottom_nav_bar_v2:
  persistent_bottom_nav_bar:


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


  assets:
    - assets/images/